"""Render a Scan + Finding[] as a Markdown report.

This is plain text — no shell-out, no headless browser, no PDF. Designed
to be drop-into-a-GitHub-issue useful: severity-grouped, each finding with
file/line, source engine, and the description verbatim from the analyzer.

We deliberately don't include the embedding-based "similar incidents"
suggestion here — that lives in a separate enrichment step (W12) and
would make this module reach into vector search. Keeping this pure-render.
"""

from __future__ import annotations

from datetime import datetime

from wr3_api.models import Finding, Scan

_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]
_SEVERITY_LABEL = {
    "critical": "🔴 CRITICAL",
    "high":     "🟠 HIGH",
    "medium":   "🟡 MEDIUM",
    "low":      "🔵 LOW",
    "info":     "⚪ INFO",
}


def render_scan_markdown(scan: Scan, findings: list[Finding]) -> str:
    """Render a single scan + its findings as Markdown text."""
    lines: list[str] = []

    # --- Header ---
    lines.append(f"# wr3 audit report")
    lines.append("")
    lines.append(f"- **Contract:** `{scan.address}`")
    lines.append(f"- **Network:** `{scan.network}`")
    if scan.score is not None:
        tier = (scan.tier or "?").upper()
        lines.append(f"- **Score:** {scan.score:.1f} / 100  ({tier})")
    if scan.duration_seconds is not None:
        lines.append(f"- **Duration:** {scan.duration_seconds:.1f}s")
    lines.append(f"- **Scanned at:** {_fmt(scan.created_at)}")
    if scan.completed_at:
        lines.append(f"- **Completed at:** {_fmt(scan.completed_at)}")
    lines.append("")

    # --- Score breakdown (axes) ---
    axes = ((scan.report or {}).get("axes") or []) if scan.report else []
    if axes:
        lines.append("## Score breakdown")
        lines.append("")
        lines.append("| Axis | Weight | Score | Rationale |")
        lines.append("|---|---:|---:|---|")
        for a in axes:
            name = str(a.get("name", "")).replace("|", "\\|")
            weight = a.get("weight")
            score = a.get("score")
            rationale = str(a.get("rationale", "")).replace("|", "\\|").replace("\n", " ")
            weight_str = f"{round(float(weight) * 100)}%" if weight is not None else "—"
            score_str = f"{float(score):.1f}" if score is not None else "—"
            lines.append(f"| {name} | {weight_str} | {score_str} | {rationale} |")
        lines.append("")

    # --- Findings, grouped by severity ---
    active = [f for f in findings if not f.dismissed]
    dismissed = [f for f in findings if f.dismissed]

    lines.append(f"## Findings  ({len(active)} active, {len(dismissed)} dismissed by triage)")
    lines.append("")

    if not active:
        lines.append("> No active findings. Either the contract is clean or all matches were filtered by triage.")
        lines.append("")
    else:
        grouped: dict[str, list[Finding]] = {s: [] for s in _SEVERITY_ORDER}
        for f in active:
            grouped.setdefault(f.severity.lower(), []).append(f)
        for sev in _SEVERITY_ORDER:
            bucket = grouped.get(sev, [])
            if not bucket:
                continue
            lines.append(f"### {_SEVERITY_LABEL[sev]}  ({len(bucket)})")
            lines.append("")
            for f in bucket:
                lines.extend(_render_finding(f))
                lines.append("")

    if dismissed:
        lines.append("---")
        lines.append("")
        lines.append("<details>")
        lines.append(f"<summary>Dismissed by triage ({len(dismissed)})</summary>")
        lines.append("")
        for f in dismissed:
            lines.extend(_render_finding(f))
            lines.append("")
        lines.append("</details>")
        lines.append("")

    # --- Disclaimer ---
    lines.append("---")
    lines.append("")
    disclaimer = (
        ((scan.report or {}).get("disclaimer") if scan.report else None)
        or (
            "_AI-assisted audit results are best-effort and not a replacement "
            "for human review. wr3 provides no warranty._"
        )
    )
    lines.append(disclaimer)
    lines.append("")
    lines.append(f"_Generated by wr3 — scan id `{scan.id}`._")

    return "\n".join(lines)


def _render_finding(f: Finding) -> list[str]:
    out: list[str] = []
    location = f.source_engine
    if f.line is not None:
        location += f":{f.line}"
    badges: list[str] = []
    if f.poc_validated:
        badges.append("**PoC ✓**")
    badge_str = " · " + " · ".join(badges) if badges else ""

    out.append(f"#### {f.title}")
    out.append("")
    out.append(
        f"`{location}` · confidence {round(f.confidence * 100)}%{badge_str}"
    )
    if f.file:
        out.append(f"file: `{f.file}`")
    if f.description:
        out.append("")
        out.append(f.description.strip())
    return out


def _fmt(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M UTC")
